import React from 'react';

const Resume = () => {
  return (
    <div className="section">
      <div className="section-header">===== RESUME =====</div>
        <ul className="resume-experience-content">
          <li>
            <h2>> SOFTWARE ENGINEER</h2>
            <h3>Undertone</h3>
            <h4>New York, NY</h4>
            <h4>5/2019 - 1/2020</h4>
            <p>• Developed features and fixes for multiple React, Redux and Node based platforms.</p>
            <p>• Increased data reliability and error response time by building cron job monitors in Node to detect issues with external APIs and Redis sync processes.</p>
            <p>• Created SQL scripts to perform manual backend updates by user request.</p>
            <p>• Authored and maintained detailed REST API and application dataflow documentation for internal and user reference.</p>
            <p>• Monitored log activity and cached data in AWS, Kubernetes, and Kibana dashboards to quickly debug issues.</p>
          </li>
          <li>
            <h2>> Technical Support Specialist</h2>
            <h3>Conxeo</h3>
            <h4>Tarrytown, NY</h4>
            <h4>2/2017 - 11/2018</h4>
            <p>• Developed Zendesk triggers to send automated replies generated by ticket content.</p>
            <p>• Created custom solution templates for clients based on support ticket history.</p>
          </li>
          <li>
            <h2>> Customer Technical Support Specialist</h2>
            <h3>Turtle Beach Corp</h3>
            <h4>Valhalla, NY</h4>
            <h4>11/2011 - 2/2017</h4>
            <p>• Proposed, built and launched a new Turtle Beach Support Website in jQuery, HTML and CSS, which resulted in a 30% decrease of incoming support tickets.</p>
            <p>• Created over 200 support articles, FAQs, and troubleshooting diagrams for the Turtle Beach Support Website.</p>
            <p>• Improved SEO and web rankings for the support website by monitoring search and visitor analytics.</p>
            <p></p>
          </li>
        </ul>
        <ul className="resume-education-content">
          <li>
            <h2>> Full Stack Engineering Immersive - Grace Hopper Program</h2>
            <h3>Fullstack Academy</h3>
            <h4>New York, NY</h4>
            <h4>1/2018 - 4/2018</h4>
            <p>Developed full-stack applications using Javascript, React, Redux, Node, Postgres, React Native, and Viromedia AR.</p>
          </li>
          <li>
            <h2>> Computer Science Curriculum</h2>
            <h3>SUNY WCC</h3>
            <h4>Valhalla, NY</h4>
            <h4>Attd. 1/2014 - 5/2017</h4>
            <p>Courses: Computer Programming (C++), Web Programming, GUI Development, Java Development, Linux Operating Systems, Data Structures</p>
          </li>
        </ul>
      <div className="section-footer">====== END =======</div>
    </div>
  );
};

export default Resume;
